# Dockerfile pour le backend
FROM eclipse-temurin:17-jdk-alpine

# Installation des dépendances système
# Ajout de 'dos2unix' pour garantir le formatage correct des scripts
RUN apk add --no-cache curl jq bash dos2unix

# Définir le répertoire de travail
WORKDIR /app

# Copier le JAR
COPY event-0.0.1-SNAPSHOT.jar /app/

# Copier les scripts depuis le dossier src local vers le conteneur
COPY src/init_data.sh /app/
COPY src/startup.sh /app/

# Normalisation des fins de ligne (CRLF -> LF) et attribution des droits d'exécution
RUN dos2unix /app/startup.sh /app/init_data.sh && \
    chmod +x /app/startup.sh /app/init_data.sh

# Exposer le port 8080
EXPOSE 8080

# Utiliser le script de démarrage
CMD ["./startup.sh"]